### ISSUE TITLE
Upload to steam

### ISSUE THREAD

**Issue by Shadowblitz16** [rl-starbound/rl_fieldcontrol#1]
Can you upload this to steam workshop?

**Comment by Shadowblitz16** [comment]
I uploaded this to steam workshop. 
Let me know if you want me to make it private or not.
Also gave credits.

![image](https://user-images.githubusercontent.com/2453707/176257635-ee2c3a3e-c8b5-4398-9a8e-991136dd9d85.png)

**Comment by countlessCritters** [comment]
Adding the link for future convenience: https://steamcommunity.com/sharedfiles/filedetails/?id=2826680792

**Comment by rl-starbound** [comment]
I don't use Steam, but this looks fine to me. I'll mention you if/when I update the code so that you can upload a new version.

**Comment by rl-starbound** [comment]
For future reference, it's been reported to me that the original Steam copy of this mod was broken, and a fixed copy was uploaded to a new Steam mod at this address: https://steamcommunity.com/sharedfiles/filedetails/?id=2828090039

The old Steam mod should be abandoned in favor of this copy.

**Comment by Shadowblitz16** [comment]
@rl-starbound yes my brother helped me upload that.
I am on linux so I don't have the starbound mod tool which my brother does since he is on windows.

I couldn't find a way to update the old mod so we just uploaded a new one.
