### ISSUE TITLE
Boot Back to Title Screen on Interaction with Field Control Console

### ISSUE THREAD

**Issue by countlessCritters** [rl-starbound/rl_fieldcontrol#2]
Error message is `(AssetException) Error loading asset/interface/scripted/rl_fieldcontrolconsole/rl_fieldcontrolconsolegui.config`
Also found the following in starbound.log when loading in after selecting my character: `[Error] Exception while creating lua context for scripts '('/wired/rl_fieldcontrolconsole/rl_fieldcontrolconsole.lua')': (LuaException) Error code 2, [string "/wired/rl_fieldcontrolconsole/rl_fieldcontrol..."]:1: (AssetException) Error loading asset /scripts/rl_fieldcontrol.lua`

**Comment by rl-starbound** [comment]
Can you upload/attach the full starbound.log file to this issue? The Field Control Console works fine for me, and I can't see enough context to tell why it isn't working for you.

**Comment by countlessCritters** [comment]
Sorry for the delay! It's heavily modded so if it looks like another mod is at fault, I'd honestly rather try to do it myself than ask you to sift through all that.
[starbound.log](https://github.com/rl-starbound/rl_fieldcontrol/files/9007139/starbound.log)

**Comment by rl-starbound** [comment]
Based on the errors, it looks like the file `/scripts/rl_fieldcontrol.lua` is missing. That's odd, because you can clearly see in this repo that it's there. Maybe your download got corrupted somehow? Does uninstalling and reinstalling this mod fix it? If not, can you check manually in your mods directory to see if the file is present? (I'm not sure how Steam stores mods, but it's probably either as `.pak` files or just as directories of mods. Perhaps someone else can fill in more instructions if you need them.)

**Comment by countlessCritters** [comment]
Okay, found the issue, and the fix. The steam version Shadowblitz uploaded isn't a .pak file and is instead identical to the repo in file structure. For some reason that causes a problem specifically with loading scripts, and making it a .pak file fixed it. I'll give them the .pak file and close this issue.

**Comment by rl-starbound** [comment]
Good catch. I'm surprised this didn't totally fail to load at startup. I never meant for this repo structure to be used directly, but rather for users to use the makefile to build the pak file.

**Comment by rl-starbound** [comment]
For future reference, it's been reported to me that a fixed copy of this mod was uploaded to a new Steam mod at this address: https://steamcommunity.com/sharedfiles/filedetails/?id=2828090039

The old Steam mod should be abandoned in favor of this copy.
