### ISSUE TITLE
ctd

### ISSUE THREAD

**Issue by DougStoker** [rl-starbound/rl_fieldcontrol#3]
[22:50:14.656] [Error] Application: exception thrown, shutting down: (StagehandDatabaseException) Error loading stagehand type '/stagehands/rl_fieldmanager.stagehand'

**Comment by rl-starbound** [comment]
Please attach a starbound.log to this issue so I can see the full context of what went wrong.

Also, it's my understanding that the first version of this mod that was uploaded to Steam was corrupted (see issue #2 for more on this). They've now uploaded a fixed version, but to a new Steam mod. Assuming you're using the mod from Steam, please make sure that you're using this version: https://steamcommunity.com/sharedfiles/filedetails/?id=2828090039

**Comment by rl-starbound** [comment]
Closing this due to no response from the reporter in over two years.
